/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.*;
import javax.swing.*;
/**
 *
 * @author Sachin Kumar
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        
        initComponents();
        LpassField.setEchoChar( (char) 0);
        LForgetField.setText("<html>Forget Password ?</html>");
        LForgetField.setAlignmentX(RIGHT_ALIGNMENT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        LaccountField = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        LForgetField = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        LpassField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LAXMI CHIT FUND");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(828, 715));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(176, 82, 240));

        jLabel4.setBackground(new java.awt.Color(153, 0, 255));
        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank_icon.gif"))); // NOI18N
        jLabel4.setMaximumSize(new java.awt.Dimension(52, 52));
        jLabel4.setMinimumSize(new java.awt.Dimension(52, 52));
        jLabel4.setPreferredSize(new java.awt.Dimension(52, 52));
        jPanel2.add(jLabel4);

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel1.setText("Bank Managment System");
        jPanel2.add(jLabel1);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 828, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_new.gif"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 72, 546, -1));

        jButton2.setBackground(new java.awt.Color(176, 82, 240));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("Create Account");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(79, 211, 112), 0));
        jButton2.setFocusPainted(false);
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(704, 440, 110, 40));

        LaccountField.setForeground(new java.awt.Color(120, 120, 120));
        LaccountField.setText(" Account Number");
        LaccountField.setToolTipText("Account Number");
        LaccountField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(100, 100, 100), 2, true));
        LaccountField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LaccountFieldMouseClicked(evt);
            }
        });
        LaccountField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaccountFieldActionPerformed(evt);
            }
        });
        LaccountField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LaccountFieldKeyPressed(evt);
            }
        });
        jPanel1.add(LaccountField, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 263, 240, 42));

        jButton3.setBackground(new java.awt.Color(176, 82, 240));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setText("Login");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 440, 120, 40));

        LForgetField.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        LForgetField.setForeground(new java.awt.Color(51, 153, 0));
        LForgetField.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LForgetField.setText("Forget Password ?");
        LForgetField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LForgetFieldMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LForgetFieldMouseExited(evt);
            }
        });
        jPanel1.add(LForgetField, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 380, 100, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Login");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 191, -1, 43));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mini login.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(639, 199, -1, 27));

        LpassField.setForeground(new java.awt.Color(120, 120, 120));
        LpassField.setText("Password");
        LpassField.setToolTipText("Password");
        LpassField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(100, 100, 100), 2, true));
        LpassField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                LpassFieldFocusGained(evt);
            }
        });
        LpassField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LpassFieldKeyPressed(evt);
            }
        });
        jPanel1.add(LpassField, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 326, 240, 41));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(874, 645));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void LForgetFieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LForgetFieldMouseEntered
        // TODO add your handling code here:
        LForgetField.setText("<html><U>Forget Password ?</U></html>");
        LForgetField.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        LForgetField.setForeground(new java.awt.Color(50, 82, 240));
       

    }//GEN-LAST:event_LForgetFieldMouseEntered

    Boolean B2=true;
    private void LaccountFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LaccountFieldMouseClicked
        // TODO add your handling code here:
        if(B2){
        LaccountField.setText("");
        B2=false;
        }
    }//GEN-LAST:event_LaccountFieldMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       new Registration().setVisible(true);
       this.setVisible(false);
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void LaccountFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaccountFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LaccountFieldActionPerformed

    Boolean B1=true;
    private void LaccountFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LaccountFieldKeyPressed
        // TODO add your handling code here:
         int key=evt.getKeyChar();
         
        if(B1 && key >='0' && key <='9' ){
            LaccountField.setText("");
            LaccountField.setEditable(true);
            B1=false;
            B2=false;
        }else{
           
            if( key >='0' && key <='9'){
                LaccountField.setEditable(true);
                LaccountField.setForeground(new java.awt.Color(0, 0, 0));
            }else{
                LaccountField.setEditable(false);
            }
        }
    }//GEN-LAST:event_LaccountFieldKeyPressed

    
    private void LpassFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LpassFieldKeyPressed
        // TODO add your handling code here:
         int key= evt.getKeyCode();
        
         if( key==10){
            //comparision yahan pr krio next screen pr jaane ke liye
             this.setVisible(false);
            new Registration().setVisible(true);
        }else{
            LpassField.setEchoChar('*');
            LpassField.setForeground(new java.awt.Color(0, 0, 0));
        }
    }//GEN-LAST:event_LpassFieldKeyPressed
    Boolean B4=true;
    private void LpassFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LpassFieldFocusGained
        // TODO add your handling code here:
        if(B4){
            LpassField.setText("");
            B4=false;
            
        }
        
    }//GEN-LAST:event_LpassFieldFocusGained

    private void jButton3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyPressed
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_jButton3KeyPressed

    private void LForgetFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LForgetFieldMouseExited
        // TODO add your handling code here:
        LForgetField.setText("<html>Forget Password ?</html>");
        LForgetField.setForeground(new java.awt.Color(51, 153, 0));
    }//GEN-LAST:event_LForgetFieldMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LForgetField;
    private javax.swing.JTextField LaccountField;
    private javax.swing.JPasswordField LpassField;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
