import java.awt.Cursor;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Sachin Kumar
 */
public class Registration extends javax.swing.JFrame {

    /**
     * Creates new form Registration
     */
    Connection con =null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    public Registration() {
        initComponents();
        con = database.db();
        RpassField1.setEchoChar( (char) 0);
        RpassField2.setEchoChar( (char) 0);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        RfirstName = new javax.swing.JTextField();
        RlastName = new javax.swing.JTextField();
        RemailId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        RphoneNumber = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        RaccountNumber = new javax.swing.JTextField();
        RdepositAmount = new javax.swing.JTextField();
        RpassField1 = new javax.swing.JPasswordField();
        RbackButton = new javax.swing.JButton();
        RpassField2 = new javax.swing.JPasswordField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        RconfirmButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(176, 82, 240), 5));
        jPanel1.setDoubleBuffered(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registration_new.gif"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Registration");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registration_icon.png"))); // NOI18N

        RfirstName.setForeground(new java.awt.Color(120, 120, 120));
        RfirstName.setText(" First Name");
        RfirstName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(100, 100, 100), 2, true)
        );
        RfirstName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                RfirstNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                RfirstNameFocusLost(evt);
            }
        });
        RfirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RfirstNameActionPerformed(evt);
            }
        });
        RfirstName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                RfirstNameKeyPressed(evt);
            }
        });

        RlastName.setForeground(new java.awt.Color(120, 120, 120));
        RlastName.setText(" Last Name");
        RlastName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(100, 100, 100), 2, true));
        RlastName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                RlastNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                RlastNameFocusLost(evt);
            }
        });
        RlastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RlastNameActionPerformed(evt);
            }
        });
        RlastName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                RlastNameKeyPressed(evt);
            }
        });

        RemailId.setForeground(new java.awt.Color(120, 120, 120));
        RemailId.setText(" Email Id");
        RemailId.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(100, 100, 100), 2, true));
        RemailId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                RemailIdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                RemailIdFocusLost(evt);
            }
        });
        RemailId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemailIdActionPerformed(evt);
            }
        });
        RemailId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                RemailIdKeyPressed(evt);
            }
        });

        jLabel4.setText(" Gender :");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Male");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Female");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        RphoneNumber.setForeground(new java.awt.Color(120, 120, 120));
        RphoneNumber.setText(" Phone Number");
        RphoneNumber.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(100, 100, 100), 2, true));
        RphoneNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                RphoneNumberFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                RphoneNumberFocusLost(evt);
            }
        });
        RphoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RphoneNumberActionPerformed(evt);
            }
        });
        RphoneNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                RphoneNumberKeyPressed(evt);
            }
        });

        jLabel5.setText(" Date Of Birth :");

        RaccountNumber.setForeground(new java.awt.Color(120, 120, 120));
        RaccountNumber.setText(" Account Number");
        RaccountNumber.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(100, 100, 100), 2, true));
        RaccountNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                RaccountNumberFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                RaccountNumberFocusLost(evt);
            }
        });
        RaccountNumber.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RaccountNumberMouseClicked(evt);
            }
        });
        RaccountNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RaccountNumberActionPerformed(evt);
            }
        });
        RaccountNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                RaccountNumberKeyPressed(evt);
            }
        });

        RdepositAmount.setForeground(new java.awt.Color(120, 120, 120));
        RdepositAmount.setText(" Deposit Amount");
        RdepositAmount.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(100, 100, 100), 2, true));
        RdepositAmount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                RdepositAmountFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                RdepositAmountFocusLost(evt);
            }
        });
        RdepositAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdepositAmountActionPerformed(evt);
            }
        });
        RdepositAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                RdepositAmountKeyPressed(evt);
            }
        });

        RpassField1.setForeground(new java.awt.Color(120, 120, 120));
        RpassField1.setText(" Password");
        RpassField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(100, 100, 100), 2, true));
        RpassField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                RpassField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                RpassField1FocusLost(evt);
            }
        });
        RpassField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                RpassField1KeyPressed(evt);
            }
        });

        RbackButton.setBackground(new java.awt.Color(176, 82, 240));
        RbackButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RbackButton.setText("Back");
        RbackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RbackButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RbackButtonMouseExited(evt);
            }
        });
        RbackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbackButtonActionPerformed(evt);
            }
        });

        RpassField2.setForeground(new java.awt.Color(120, 120, 120));
        RpassField2.setText(" Confirm Password");
        RpassField2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(100, 100, 100), 2, true));
        RpassField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                RpassField2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                RpassField2FocusLost(evt);
            }
        });
        RpassField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RpassField2ActionPerformed(evt);
            }
        });
        RpassField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                RpassField2KeyPressed(evt);
            }
        });

        jDateChooser1.setDateFormatString("yyyy-MM-dd");

        RconfirmButton.setBackground(new java.awt.Color(176, 82, 240));
        RconfirmButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RconfirmButton.setText("Confirm");
        RconfirmButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RconfirmButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RconfirmButtonMouseExited(evt);
            }
        });
        RconfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RconfirmButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(RbackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RconfirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(RpassField1)
                        .addComponent(RdepositAmount)
                        .addComponent(RaccountNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                        .addComponent(RfirstName)
                        .addComponent(RemailId)
                        .addComponent(RlastName, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(RphoneNumber, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel3))
                        .addComponent(RpassField2, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(RaccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RfirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RlastName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RemailId, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RphoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RdepositAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RpassField1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RpassField2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RbackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RconfirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(860, 638));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RfirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RfirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RfirstNameActionPerformed

    private void RemailIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemailIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RemailIdActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void RlastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RlastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RlastNameActionPerformed

    private void RphoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RphoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RphoneNumberActionPerformed

    private void RaccountNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RaccountNumberActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_RaccountNumberActionPerformed

    private void RbackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbackButtonActionPerformed
    
        new Login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_RbackButtonActionPerformed

    private void RdepositAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdepositAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RdepositAmountActionPerformed

    Boolean B2= true;
    private void RaccountNumberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RaccountNumberMouseClicked
        // TODO add your handling code here:
        if(RaccountNumber.getText().equals( " Account Number")){
            RaccountNumber.setText("");
            B2=false;
        }
        RaccountNumber.setEditable(true);
    }//GEN-LAST:event_RaccountNumberMouseClicked

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
  
        
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    Boolean B1=true;
    private void RaccountNumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RaccountNumberKeyPressed
        // TODO add your handling code here:
        int key=evt.getKeyChar();
         
        if( key >='0' && key <='9' || evt.getKeyCode() == java.awt.event.KeyEvent.VK_BACK_SPACE ){
            if(B1){
                RaccountNumber.setText("");
            }
             RaccountNumber.setEditable(true);
             RaccountNumber.setForeground(new java.awt.Color(0, 0, 0));
            B1=false;
            B2=false;
        }else{       
            RaccountNumber.setEditable(false);   
        }
    }//GEN-LAST:event_RaccountNumberKeyPressed
   
    private void RfirstNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_RfirstNameFocusGained
        // TODO add your handling code here:
        if( RfirstName.getText().equals(" First Name")){
            RfirstName.setText("");
        }
    }//GEN-LAST:event_RfirstNameFocusGained
    
   
    private void RlastNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_RlastNameFocusGained
         // TODO add your handling code here:
        if(RlastName.getText().equals(" Last Name")){
            RlastName.setText("");
        }
    }//GEN-LAST:event_RlastNameFocusGained
    
   
    private void RemailIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_RemailIdFocusGained
       // TODO add your handling code here:
        if( RemailId.getText().equals(" Email Id")){
            RemailId.setText("");
         
        }
    }//GEN-LAST:event_RemailIdFocusGained
    
   
    private void RphoneNumberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_RphoneNumberFocusGained
        // TODO add your handling code here:                                    
        // TODO add your handling code here:
        if(RphoneNumber.getText().equals(" Phone Number")){
            RphoneNumber.setText("");
           
        }
    }//GEN-LAST:event_RphoneNumberFocusGained

    private void RphoneNumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RphoneNumberKeyPressed
        // TODO add your handling code here:
        int key=evt.getKeyChar();
         
        if( key >='0' && key <='9' || evt.getKeyCode() == java.awt.event.KeyEvent.VK_BACK_SPACE ){
             RphoneNumber.setEditable(true);
             RphoneNumber.setForeground(new java.awt.Color(0, 0, 0));
           
        }else{       
            RphoneNumber.setEditable(false);   
        }
    }//GEN-LAST:event_RphoneNumberKeyPressed

    private void RdepositAmountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RdepositAmountKeyPressed
        // TODO add your handling code here:
        int key=evt.getKeyChar();
         
        if( key >='0' && key <='9' || evt.getKeyCode() == java.awt.event.KeyEvent.VK_BACK_SPACE ){
             RdepositAmount.setEditable(true);
             RdepositAmount.setForeground(new java.awt.Color(0, 0, 0));
            
        }else{       
            RdepositAmount.setEditable(false);   
        }
    }//GEN-LAST:event_RdepositAmountKeyPressed

  
    private void RdepositAmountFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_RdepositAmountFocusGained
                // TODO add your handling code here:
        if(  RdepositAmount.getText().equals(" Deposit Amount")){
            RdepositAmount.setText("");
        }
    }//GEN-LAST:event_RdepositAmountFocusGained

        
    private void RpassField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_RpassField1FocusGained
        // TODO add your handling code here:
    
        if( new String(RpassField1.getPassword()).equals(" Password")){
            RpassField1.setText("");
            RpassField1.setEchoChar('*');
           
        }
    }//GEN-LAST:event_RpassField1FocusGained

    
    private void RpassField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_RpassField2FocusGained
        // TODO add your handling code here:
        
        if(new  String( RpassField2.getPassword()).equals(" Confirm Password")){
                RpassField2.setEchoChar( '*');
                RpassField2.setForeground(new java.awt.Color(0, 0, 0));
                RpassField2.setText("");
        }
    }//GEN-LAST:event_RpassField2FocusGained

    private void RconfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RconfirmButtonActionPerformed
        // TODO add your handling code here:
        
            try {
                
                String sql = "insert into AccountDetails values(?,?,?,?,?,?,?,?,?);";
                pst = con.prepareStatement(sql);
                String gender="";
                if(jRadioButton1.isSelected())
                {
                    gender = "Male";
                }
                if(jRadioButton2.isSelected())
                {
                    gender = "Female";
                }
                pst.setString(1,RaccountNumber.getText());
                pst.setString(2,RfirstName.getText());
                pst.setString(3,RlastName.getText());
                pst.setString(4,RemailId.getText());
                pst.setString(5,gender);
                pst.setString(6,RphoneNumber.getText());
                pst.setString(7,((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText());
                pst.setString(8,RdepositAmount.getText());
                pst.setString(9,new String(RpassField1.getPassword()));
                
                if(new String(RpassField1.getPassword()).equals(new String(RpassField2.getPassword())))
                {
                    
                   int p=JOptionPane.showConfirmDialog(null, "Are you Sure to save?","Confirm",JOptionPane.YES_NO_OPTION);
                   if(p==0)
                   {
                       pst.execute();
                       JOptionPane.showMessageDialog(null,"Account created sucessfully ");
                       new Login().setVisible(true);
                       this.setVisible(false);
                       this.dispose();
                   }
                   else
                   {
                       this.setVisible(true);
                   }
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Password not matched please check ! ");
                }
                
                
            }
            catch (SQLException e){
                JOptionPane.showMessageDialog(null,e.getMessage());
            }
        
    }//GEN-LAST:event_RconfirmButtonActionPerformed

    private void RaccountNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_RaccountNumberFocusLost
        // TODO add your handling code here:
        if(RaccountNumber.getText().equals("")){
            RaccountNumber.setForeground(new java.awt.Color(120, 120, 120));
            RaccountNumber.setText(" Account Number"); 
            
        }
        B2=false;
    }//GEN-LAST:event_RaccountNumberFocusLost

    private void RaccountNumberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_RaccountNumberFocusGained
        // TODO add your handling code here:
        if(RaccountNumber.getText().equals(" Account Number") && B2==false){
            RaccountNumber.setText("");
        }
    }//GEN-LAST:event_RaccountNumberFocusGained

    private void RfirstNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_RfirstNameFocusLost
        // TODO add your handling code here:
        if(RfirstName.getText().equals("")){
            RfirstName.setForeground(new java.awt.Color(120, 120, 120));
            RfirstName.setText(" First Name");
        }
    }//GEN-LAST:event_RfirstNameFocusLost

    private void RlastNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_RlastNameFocusLost
        // TODO add your handling code here:
        if(RlastName.getText().equals("")){
            RlastName.setForeground(new java.awt.Color(120, 120, 120));
            RlastName.setText(" Last Name");
        }
    }//GEN-LAST:event_RlastNameFocusLost

    private void RemailIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_RemailIdFocusLost
        // TODO add your handling code here:
        if(RemailId.getText().equals("")){
           RemailId.setForeground(new java.awt.Color(120, 120, 120));
            RemailId.setText(" Email Id");
        }
    }//GEN-LAST:event_RemailIdFocusLost

    private void RphoneNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_RphoneNumberFocusLost
        // TODO add your handling code here:
        if(RphoneNumber.getText().equals("")){
            RphoneNumber.setText(" Phone Number");
        }
    }//GEN-LAST:event_RphoneNumberFocusLost

    private void RdepositAmountFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_RdepositAmountFocusLost
        // TODO add your handling code here:
        if(RdepositAmount.getText().equals("")){
            RdepositAmount.setText(" Deposit Amount");
        }
    }//GEN-LAST:event_RdepositAmountFocusLost

    private void RpassField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_RpassField1FocusLost
        // TODO add your handling code here:
        if(new  String( RpassField1.getPassword()).equals("")){
                RpassField1.setEchoChar( (char) 0);
                RpassField1.setForeground(new java.awt.Color(120, 120, 120));
                RpassField1.setText(" Password");
        }
    }//GEN-LAST:event_RpassField1FocusLost

    private void RpassField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_RpassField2FocusLost
        // TODO add your handling code here:
        if(new  String( RpassField2.getPassword()).equals("")){
                RpassField2.setEchoChar( (char) 0);
                
                RpassField2.setText(" Confirm Password");
                RpassField2.setForeground(new java.awt.Color(120, 120, 120));
        }
    }//GEN-LAST:event_RpassField2FocusLost

    private void RfirstNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RfirstNameKeyPressed
        // TODO add your handling code here:
        RfirstName.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_RfirstNameKeyPressed

    private void RlastNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RlastNameKeyPressed
        // TODO add your handling code here:
       RlastName.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_RlastNameKeyPressed

    private void RemailIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RemailIdKeyPressed
        // TODO add your handling code here:
        RemailId.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_RemailIdKeyPressed

    private void RpassField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RpassField1KeyPressed
        // TODO add your handling code here:
        RpassField1.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_RpassField1KeyPressed

    private void RpassField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RpassField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RpassField2ActionPerformed

    private void RpassField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RpassField2KeyPressed
        // TODO add your handling code here:
        RpassField2.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_RpassField2KeyPressed

    private void RbackButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RbackButtonMouseEntered
        // TODO add your handling code here:
        RbackButton.setBackground(new java.awt.Color(51,153, 0));
        RbackButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        
    }//GEN-LAST:event_RbackButtonMouseEntered

    private void RbackButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RbackButtonMouseExited
        // TODO add your handling code here:
        RbackButton.setBackground(new java.awt.Color(176, 82, 240));
    }//GEN-LAST:event_RbackButtonMouseExited

    private void RconfirmButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RconfirmButtonMouseEntered
        // TODO add your handling code here:
        RconfirmButton.setBackground(new java.awt.Color(51,153, 0));
        RconfirmButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_RconfirmButtonMouseEntered

    private void RconfirmButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RconfirmButtonMouseExited
        // TODO add your handling code here:
        RconfirmButton.setBackground(new java.awt.Color(176, 82, 240));
    }//GEN-LAST:event_RconfirmButtonMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Registration().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField RaccountNumber;
    private javax.swing.JButton RbackButton;
    private javax.swing.JButton RconfirmButton;
    private javax.swing.JTextField RdepositAmount;
    private javax.swing.JTextField RemailId;
    private javax.swing.JTextField RfirstName;
    private javax.swing.JTextField RlastName;
    private javax.swing.JPasswordField RpassField1;
    private javax.swing.JPasswordField RpassField2;
    private javax.swing.JTextField RphoneNumber;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    // End of variables declaration//GEN-END:variables
}
