/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.Cursor;
import javax.swing.JOptionPane;
import java.sql.*;
import java.awt.event.KeyEvent;
import java.awt.Color;
import javax.swing.text.Caret;

/**
 *
 * @author Sachin Kumar
 */
public class ResetPassword extends javax.swing.JFrame {

    /**
     * Creates new form ResetPassword
     */
    Connection con = null;
    Statement stm = null;
    ResultSet rs = null;

    public ResetPassword() {
        initComponents();
        con = database.db();
        VaccountNumber.setCaretPosition(1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        VaccountNumber = new javax.swing.JTextField();
        VPhoneField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reset Password");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(176, 82, 240), 8));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/find_user.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(176, 82, 240));
        jLabel2.setText("First Check It's You");

        VaccountNumber.setForeground(new java.awt.Color(120, 120, 120));
        VaccountNumber.setText(" Enter UserName");
        VaccountNumber.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(100, 100, 100), 2, true));
        VaccountNumber.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                VaccountNumberCaretUpdate(evt);
            }
        });
        VaccountNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                VaccountNumberFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                VaccountNumberFocusLost(evt);
            }
        });
        VaccountNumber.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VaccountNumberMouseClicked(evt);
            }
        });
        VaccountNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VaccountNumberActionPerformed(evt);
            }
        });
        VaccountNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                VaccountNumberKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                VaccountNumberKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                VaccountNumberKeyTyped(evt);
            }
        });

        VPhoneField.setForeground(new java.awt.Color(120, 120, 120));
        VPhoneField.setText(" Enter Phone Number");
        VPhoneField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(100, 100, 100), 2, true));
        VPhoneField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                VPhoneFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                VPhoneFieldFocusLost(evt);
            }
        });
        VPhoneField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VPhoneFieldMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VPhoneFieldMouseEntered(evt);
            }
        });
        VPhoneField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VPhoneFieldActionPerformed(evt);
            }
        });
        VPhoneField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                VPhoneFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                VPhoneFieldKeyReleased(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(176, 82, 240));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("Verify User");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(134, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(176, 176, 176))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VaccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(VPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(120, 120, 120))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(166, 166, 166))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addComponent(VaccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(VPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(483, 527));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void VaccountNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VaccountNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VaccountNumberActionPerformed

    private void VPhoneFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VPhoneFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VPhoneFieldActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        Login.jframe.setEnabled(true);
    }//GEN-LAST:event_formWindowClosed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            stm = con.createStatement();
            String username = VaccountNumber.getText().trim();
            String phone = VPhoneField.getText().trim();

            String sql = "select * from AccountDetails where Username = '" + username + "' and Phone ='" + phone + "'; ";

            rs = stm.executeQuery(sql);
            if (rs.next()) {
                String pass = rs.getString("Password");
                JOptionPane.showMessageDialog(null, "Your password is '" + pass + "'", "Password", 1);
                new Login().setVisible(true);

                this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(null, "Wrong Account Number or Phone Number !!", "Reset Failed", 2);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error !", 2);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void VaccountNumberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VaccountNumberMouseClicked
        // TODO add your handling code here:

        if (VaccountNumber.getText().equals(" Enter Account Number")) {
            VaccountNumber.setCaretPosition(1);
        }

    }//GEN-LAST:event_VaccountNumberMouseClicked

    private void VaccountNumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_VaccountNumberKeyPressed
        // TODO add your handling code here:
        int key = evt.getKeyCode();
        VaccountNumber.setEditable(true);
        int pos = VaccountNumber.getCaretPosition();

        if ((key == 37 && pos == 1) || (key == 39 || key == 40 || key == 38) && VaccountNumber.getText().equals(" Enter UserName")) {
            evt.consume();
        } else if (key == KeyEvent.VK_SPACE) {
            VaccountNumber.setEditable(false);
        } else if ((key == KeyEvent.VK_BACK_SPACE && VaccountNumber.getText().equals(" Enter UserName")) || (pos == 1 && VaccountNumber.getText().length() >= 2 && key == KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
        } else if (VaccountNumber.getText().equals(" Enter UserName")) {
            VaccountNumber.setForeground(new Color(0, 0, 0));
            VaccountNumber.setEditable(true);
            VaccountNumber.setText(" ");
        } else if (VaccountNumber.getText().length() == 2 && evt.getKeyCode() == java.awt.event.KeyEvent.VK_BACK_SPACE && pos == 2) {
            VaccountNumber.setForeground(new Color(120, 120, 120));
            VaccountNumber.setText("  Enter UserName");
            VaccountNumber.setCaretPosition(2);
        }
    }//GEN-LAST:event_VaccountNumberKeyPressed


    private void VaccountNumberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_VaccountNumberFocusGained
        // TODO add your handling code here:
        if (VaccountNumber.getText().equals((" Enter UserName"))) {
            VaccountNumber.setCaretPosition(1);
        }

    }//GEN-LAST:event_VaccountNumberFocusGained

    private void VaccountNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_VaccountNumberFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_VaccountNumberFocusLost

    private void VPhoneFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_VPhoneFieldFocusGained
        // TODO add your handling code here:
        if (VPhoneField.getText().equals(" Enter Phone Number")) {
            VPhoneField.setCaretPosition(1);
        }

    }//GEN-LAST:event_VPhoneFieldFocusGained

    private void VPhoneFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_VPhoneFieldFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_VPhoneFieldFocusLost

    private void VPhoneFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_VPhoneFieldKeyPressed
        // TODO add your handling code here:

        int key = evt.getKeyCode();

        VPhoneField.setEditable(true);
        int pos = VPhoneField.getCaretPosition();
        if (VPhoneField.getText().length() > 10) {
            if (key == 37 && pos != 1) {
                VPhoneField.setCaretPosition(pos - 1);
                evt.consume();
                return;
            } else if (key == 39) {
                VPhoneField.setCaretPosition(pos + 1);
                evt.consume();
                return;
            }

        }
        if ((key >= '0' && key <= '9') || key == KeyEvent.VK_BACK_SPACE || (key == 37 || key == 39)) {

            if ((key == 37 && pos == 1) || (key == 39 && VPhoneField.getText().equals(" Enter Phone Number"))) {
                evt.consume();
            } else if (key == KeyEvent.VK_SPACE) {
                VPhoneField.setEditable(false);
            } else if ((key == KeyEvent.VK_BACK_SPACE && VPhoneField.getText().equals(" Enter Phone Number")) || (pos == 1 && VPhoneField.getText().length() >= 2 && key == KeyEvent.VK_BACK_SPACE)) {
                evt.consume();
            } else if (VPhoneField.getText().equals(" Enter Phone Number")) {
                VPhoneField.setForeground(new Color(0, 0, 0));
                VPhoneField.setEditable(true);
                VPhoneField.setText(" ");
            } else if (VPhoneField.getText().length() == 2 && key == KeyEvent.VK_BACK_SPACE && pos == 2) {
                VPhoneField.setForeground(new Color(120, 120, 120));
                VPhoneField.setText("  Enter Phone Number");
                VPhoneField.setCaretPosition(2);
            } else if (!VPhoneField.getText().equals(" Enter Phone Number") && VPhoneField.getText().length() > 10 && key != KeyEvent.VK_BACK_SPACE) {
                VPhoneField.setEditable(false);
            }
        } else {
            VPhoneField.setEditable(false);
        }

    }//GEN-LAST:event_VPhoneFieldKeyPressed

    private void VPhoneFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VPhoneFieldMouseClicked
        // TODO add your handling code here:
        Caret caret = VPhoneField.getCaret();
        caret.setVisible(true);
    }//GEN-LAST:event_VPhoneFieldMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
        jButton1.setBackground(new java.awt.Color(51, 153, 0));
        jButton1.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        // TODO add your handling code here:
        jButton1.setBackground(new java.awt.Color(176, 82, 240));
        jButton1.setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_jButton1MouseExited

    private void VaccountNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_VaccountNumberKeyReleased
        // TODO add your handling code here:
        if (VaccountNumber.getText().equals("") || VaccountNumber.getText().equals(" ")) {
            VaccountNumber.setForeground(new Color(120, 120, 120));
            VaccountNumber.setText(" Enter UserName");
            VaccountNumber.setCaretPosition(1);
        }

    }//GEN-LAST:event_VaccountNumberKeyReleased

    private void VPhoneFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_VPhoneFieldKeyReleased
        // TODO add your handling code here:

        if (VPhoneField.getText().equals("") || VPhoneField.getText().equals(" ")) {
            VPhoneField.setForeground(new Color(120, 120, 120));
            VPhoneField.setText(" Enter Phone Number");
            VPhoneField.setCaretPosition(1);
        }

    }//GEN-LAST:event_VPhoneFieldKeyReleased

    private void VaccountNumberCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_VaccountNumberCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_VaccountNumberCaretUpdate

    private void VaccountNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_VaccountNumberKeyTyped
        // TODO add your handling code here:
        if (VPhoneField.getText().equals("") || VPhoneField.getText().equals(" ")) {
            VPhoneField.setForeground(new Color(120, 120, 120));
            VPhoneField.setText("  Enter Phone Number");
            VPhoneField.setCaretPosition(1);

        }
    }//GEN-LAST:event_VaccountNumberKeyTyped

    private void VPhoneFieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VPhoneFieldMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_VPhoneFieldMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ResetPassword().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField VPhoneField;
    private javax.swing.JTextField VaccountNumber;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
